/**
 * Family auto-linker — turns the import-time graph hints into actual
 * families + family_members rows.
 *
 * Wealth Elite exports carry FAMILY HEAD IWELL CODE for each client.
 * When client X's metadata.source_family_head_code == client Y's
 * metadata.source_platform_code, Y is X's family head.
 *
 * What this module does (one Supabase round-trip per family group):
 *   1. Pull every client (id, display_name, age_years, marital_status, gender,
 *      metadata) — capped at 50k for safety
 *   2. Group by metadata.source_family_head_code
 *   3. For each group, locate the head (client whose
 *      metadata.source_platform_code matches the group key)
 *   4. Upsert a `families` row with head=head_client_id
 *   5. Insert family_members for every member (deduped)
 *
 * Idempotent: re-running after another import only adds NEW families
 * and NEW memberships; existing ones are left untouched.
 */

import { getSupabaseAdmin } from '@/lib/db/supabase';
import type { ClientsActor, FamilyRole } from './types';

interface LinkerClientRow {
  id: number;
  display_name: string;
  age_years: number | null;
  marital_status: string;
  gender: string;
  metadata: Record<string, unknown> | null;
}

export interface AutoLinkResult {
  scanned_clients: number;
  groups_found: number;
  families_created: number;
  families_existing: number;
  members_added: number;
  orphan_heads: { head_code: string; member_count: number }[];
}

function extractMeta(c: LinkerClientRow): { platform_code: string | null; family_head_code: string | null } {
  const m = c.metadata;
  if (!m) return { platform_code: null, family_head_code: null };
  return {
    platform_code: typeof m.source_platform_code === 'string' ? m.source_platform_code : null,
    family_head_code: typeof m.source_family_head_code === 'string' ? m.source_family_head_code : null,
  };
}

function guessRole(head: LinkerClientRow, member: LinkerClientRow): FamilyRole {
  if (head.age_years != null && member.age_years != null) {
    const diff = head.age_years - member.age_years;
    if (diff > 16 && diff < 60) return 'child';
    if (diff < -16) return 'parent';
    if (Math.abs(diff) <= 16 && head.gender !== member.gender && head.marital_status === 'married') return 'spouse';
  }
  return 'other_dependent';
}

export async function autoLinkFamilies(actor: ClientsActor): Promise<AutoLinkResult> {
  const supabase = getSupabaseAdmin();
  if (!supabase) throw new Error('Supabase not configured');

  // Pull a slim projection of every client. Supabase silently caps
  // .select().limit() at 1000 rows — must paginate via .range().
  const clients: LinkerClientRow[] = [];
  const PAGE = 1000;
  let offset = 0;
  while (offset < 100000) {
    const { data, error } = await supabase
      .from('clients')
      .select('id, display_name, age_years, marital_status, gender, metadata')
      .order('id', { ascending: true })
      .range(offset, offset + PAGE - 1);
    if (error) throw new Error(`Family-linker scan failed at offset ${offset}: ${error.message}`);
    if (!data || data.length === 0) break;
    for (const r of data) clients.push(r as LinkerClientRow);
    if (data.length < PAGE) break;
    offset += PAGE;
  }

  // Build index: platform_code → client
  const byPlatformCode = new Map<string, LinkerClientRow>();
  const memberByHead = new Map<string, LinkerClientRow[]>();
  for (const c of clients) {
    const meta = extractMeta(c);
    if (meta.platform_code) byPlatformCode.set(meta.platform_code, c);
    if (meta.family_head_code) {
      const arr = memberByHead.get(meta.family_head_code) || [];
      arr.push(c);
      memberByHead.set(meta.family_head_code, arr);
    }
  }

  let families_created = 0;
  let families_existing = 0;
  let members_added = 0;
  const orphan_heads: AutoLinkResult['orphan_heads'] = [];

  for (const [head_code, members] of memberByHead) {
    const head = byPlatformCode.get(head_code);
    if (!head) {
      orphan_heads.push({ head_code, member_count: members.length });
      continue;
    }

    // Upsert family by head
    let family_id: number;
    const { data: existing } = await supabase
      .from('families')
      .select('id')
      .eq('head_client_id', head.id)
      .limit(1)
      .maybeSingle();

    if (existing) {
      family_id = (existing as { id: number }).id;
      families_existing++;
    } else {
      const name = `${head.display_name} family`;
      const description = `Auto-linked from Wealth Elite export. Head source code: ${head_code}. Imported by ${actor.email}.`;
      const { data: created, error: insErr } = await supabase
        .from('families')
        .insert({
          // code generated by Postgres DEFAULT
          name,
          head_client_id: head.id,
          description,
          created_by_user_id: actor.user_id,
        })
        .select('id')
        .single();
      if (insErr || !created) {
        // Skip this group — log + continue so partial success works
        console.error(`[family-linker] family insert failed for head_code=${head_code}: ${insErr?.message}`);
        continue;
      }
      family_id = (created as { id: number }).id;
      families_created++;
    }

    // Add head member (deduped)
    const { data: headMembership } = await supabase
      .from('family_members')
      .select('id')
      .eq('family_id', family_id)
      .eq('client_id', head.id)
      .limit(1)
      .maybeSingle();
    if (!headMembership) {
      const { error: hmErr } = await supabase
        .from('family_members')
        .insert({ family_id, client_id: head.id, role: 'head', is_active: true });
      if (!hmErr) members_added++;
    }

    // Add the rest (deduped)
    for (const m of members) {
      if (m.id === head.id) continue;
      const { data: alreadyIn } = await supabase
        .from('family_members')
        .select('id')
        .eq('family_id', family_id)
        .eq('client_id', m.id)
        .limit(1)
        .maybeSingle();
      if (alreadyIn) continue;
      const role = guessRole(head, m);
      const { error: mErr } = await supabase
        .from('family_members')
        .insert({ family_id, client_id: m.id, role, is_active: true });
      if (!mErr) members_added++;
    }
  }

  return {
    scanned_clients: clients.length,
    groups_found: memberByHead.size,
    families_created,
    families_existing,
    members_added,
    orphan_heads,
  };
}
