import { LearningModule } from '@/types/learning';

export const riskReturnPerformanceModule: LearningModule = {
  id: 'risk-return-performance',
  title: 'Risk, Return & Performance',
  slug: 'risk-return-performance',
  icon: 'TrendingUp',
  description:
    'Learn to measure returns (CAGR, XIRR, rolling), understand risk metrics (Sharpe ratio, beta, standard deviation), and read mutual fund factsheets like a pro. Essential for comparing funds.',
  level: 'advanced',
  color: 'from-orange-500 to-red-500',
  estimatedTime: '55 min',
  sections: [
    // ── Section 1: Measuring Returns ───────────────────────────────────
    {
      id: 'measuring-returns',
      title: 'Measuring Returns — CAGR, Absolute, XIRR, Rolling Returns',
      slug: 'measuring-returns',
      content: {
        definition:
          'Return measurement is the process of quantifying the gain or loss generated by an investment over a specified period, expressed as a percentage of the original investment. Different methods — absolute return, CAGR (Compound Annual Growth Rate), XIRR (Extended Internal Rate of Return), and rolling returns — serve different purposes depending on the investment tenure, cash flow pattern, and the analytical objective. Absolute return measures the simple total percentage gain. CAGR smooths out volatility to show an annualized compounded growth rate. XIRR handles irregular cash flows typical of SIP investments. Rolling returns evaluate performance consistency across every possible holding period of a given length.',

        explanation:
          'Understanding return metrics is non-negotiable for any investor or distributor. With India\'s mutual fund AUM crossing ₹82 lakh crore as of early 2026 and the Nifty 50 having crossed 26,000+ levels, more capital than ever flows into mutual funds — and more investors than ever are misled by return numbers. Consider the case of an investor who says "the fund doubled in 5 years." The absolute return is 100%, but annualized (CAGR), that is only about 14.87% per year. Compare that with a fund that grew 80% in 3 years — the absolute return is lower, but the CAGR is roughly 21.6%, making it a significantly better performer on an annualized basis. Returns must always be compared on a like-for-like basis. For SIP investors, CAGR is misleading because money is invested at different times. Each SIP installment has a different holding period, so XIRR — which accounts for the timing of every cash flow — is the appropriate measure. When an investor asks "what is the SIP return?", the only accurate answer is the XIRR, not a simple CAGR. XIRR is especially important for SIP investors because it reflects the true annualized return considering all cash flow dates. Then there is the question of consistency. A fund may show a great 5-year point-to-point return, but what if it only performed well in the last year? Rolling returns solve this — they calculate the return for every possible 3-year or 5-year window and reveal how consistently the fund has performed across market cycles. Rolling returns remain the most reliable way to evaluate fund performance. A fund with a high average rolling return and low standard deviation of rolling returns is a truly consistent performer.',

        realLifeExample:
          'Consider the case of Ramesh, who invested a lump sum of ₹5,00,000 in a flexi-cap fund on 1st January 2019. By 1st January 2024, the value grew to ₹9,50,000. His absolute return is (9,50,000 - 5,00,000) / 5,00,000 = 90%. His CAGR is (9,50,000 / 5,00,000)^(1/5) - 1 = 13.7% per annum. His wife Priya invested ₹10,000/month via SIP over the same 5 years — a total of ₹6,00,000. Her portfolio value is ₹8,75,000. Her absolute return is 45.8%, but her XIRR (calculated using the Excel XIRR function with all 60 monthly cash flows and the final value) comes to 16.2% per annum. Why is Priya\'s XIRR higher than Ramesh\'s CAGR despite a lower absolute return? Because her later SIP installments had less time to compound, and many of her purchases happened at lower NAVs during the 2020 crash — rupee cost averaging at work. A rolling 3-year return analysis of this fund between 2016-2024 would show returns ranging from 8% to 22%, with a median around 14%. That gives far more insight than a single point-to-point number.',

        keyPoints: [
          'Absolute return is the simple total percentage gain — suitable only for holding periods under 1 year',
          'CAGR (Compound Annual Growth Rate) annualizes returns to enable fair comparison across different time periods',
          'XIRR (Extended Internal Rate of Return) is the only correct method to measure SIP returns since each installment has a different holding period',
          'Rolling returns calculate returns for every possible n-year period, revealing performance consistency across market cycles',
          'Point-to-point returns are sensitive to the start and end date chosen — they can be cherry-picked to show misleading results',
          'SEBI mandates that returns for periods exceeding 1 year must be shown as CAGR, not absolute returns',
          'A fund with a high average rolling return and low standard deviation of rolling returns is considered a consistent performer',
          'Always compare fund returns against the appropriate benchmark using the same return methodology',
        ],

        formula:
          'Absolute Return = ((Current Value - Initial Value) / Initial Value) x 100\n\nCAGR = ((Ending Value / Beginning Value)^(1/n)) - 1\nwhere n = number of years\n\nXIRR: Solves for r in the equation: Sum of [Cash Flow_i / (1+r)^((Date_i - Date_0)/365)] = 0\nwhere Cash Flow_i = each SIP installment (negative) and redemption value (positive)',

        numericalExample:
          'Absolute Return Example:\nInvested: ₹1,00,000 | Current Value: ₹1,45,000\nAbsolute Return = (1,45,000 - 1,00,000) / 1,00,000 x 100 = 45%\n\nCAGR Example:\nInvested: ₹2,00,000 on 1 Jan 2020 | Value on 1 Jan 2024: ₹3,50,000 | Period: 4 years\nCAGR = (3,50,000 / 2,00,000)^(1/4) - 1 = (1.75)^(0.25) - 1 = 1.1502 - 1 = 0.1502 = 15.02% per annum\n\nXIRR Example:\n₹10,000 SIP monthly for 12 months (total invested: ₹1,20,000)\nRedemption value after 12 months: ₹1,32,500\nUsing XIRR function with 12 outflows of -₹10,000 on each month-start and +₹1,32,500 at end:\nXIRR = approximately 19.8% per annum\n(Note: Simple absolute return would show only 10.4%, significantly understating the actual annualized return)',

        faq: [
          {
            question: 'Why is CAGR better than absolute return for comparison?',
            answer:
              'Absolute return does not account for the time period. A 50% return in 2 years is very different from 50% in 10 years. CAGR annualizes the return so investments with different holding periods can be compared on a level playing field. For example, 50% in 2 years is a CAGR of 22.5%, while 50% in 10 years is only 4.1% CAGR — clearly the first investment performed far better.',
          },
          {
            question: 'Can CAGR be used to measure SIP returns?',
            answer:
              'No, CAGR is not suitable for SIP returns. CAGR assumes a single lump-sum investment at the beginning, but in a SIP, money is invested periodically at different NAVs. Each installment has a different holding period. XIRR is the correct measure for SIP returns because it accounts for the timing and size of every cash flow. Most fund house websites and apps now show SIP XIRR.',
          },
          {
            question: 'What are rolling returns and why are they important?',
            answer:
              'Rolling returns calculate the return for every possible period of a given length within a dataset. For example, a 3-year rolling return analysis of a fund from 2010-2025 would calculate the 3-year return starting from every single day — 1 Jan 2010 to 1 Jan 2013, 2 Jan 2010 to 2 Jan 2013, and so on. This gives hundreds of data points instead of just one, showing how consistently a fund performs regardless of when the investment was made. It eliminates the bias of point-to-point returns.',
          },
          {
            question:
              'How is XIRR calculated for mutual fund SIP investments?',
            answer:
              'XIRR can be calculated using Excel or Google Sheets. All SIP investment dates and amounts are listed as negative values (outflows), and the current portfolio value is added as a positive value on today\'s date. Then the =XIRR(values, dates) function is applied. Most mutual fund platforms like MF Central, Kuvera, and Groww also calculate and display portfolio XIRR automatically.',
          },
          {
            question:
              'A fund shows 25% one-year return. Is that a reason to invest?',
            answer:
              'A single one-year return figure can be misleading because it depends entirely on which one-year period is being considered. Instead, the 3-year and 5-year rolling returns should be checked to assess consistency. It is also important to verify whether the fund outperformed its benchmark across different market cycles. A fund that consistently delivers 14-16% across rolling periods is generally more reliable than one that swings between -5% and 40%.',
          },
        ],

        mcqs: [
          {
            question:
              'An investor purchased mutual fund units worth ₹2,00,000. After 3 years, the value is ₹3,20,000. What is the CAGR?',
            options: ['20.0%', '60.0%', '16.96%', '13.33%'],
            correctAnswer: 2,
            explanation:
              'CAGR = (3,20,000 / 2,00,000)^(1/3) - 1 = (1.60)^(0.3333) - 1 = 1.1696 - 1 = 16.96%. The absolute return is 60%, but CAGR annualizes it to 16.96% per year. Option (d) is the simple average which is incorrect.',
          },
          {
            question:
              'Which return measurement method is most appropriate for evaluating SIP investments?',
            options: [
              'Absolute return',
              'CAGR',
              'XIRR',
              'Simple annualized return',
            ],
            correctAnswer: 2,
            explanation:
              'XIRR (Extended Internal Rate of Return) is the only correct method for SIP returns because each installment is made at a different date and NAV. XIRR considers the timing and amount of every cash flow, unlike CAGR which assumes a single lump-sum investment.',
          },
          {
            question:
              'As per SEBI guidelines, mutual fund returns for periods exceeding one year must be represented as:',
            options: [
              'Absolute returns',
              'Simple annualized returns',
              'Compounded annualized growth rate (CAGR)',
              'Rolling returns',
            ],
            correctAnswer: 2,
            explanation:
              'SEBI mandates that returns for periods greater than 1 year must be shown in CAGR (compounded annualized) format. Returns for periods less than 1 year must be shown as absolute returns and cannot be annualized, to prevent misleading representation.',
          },
          {
            question:
              'Rolling returns analysis is preferred over point-to-point returns because:',
            options: [
              'Rolling returns always show higher numbers',
              'Rolling returns eliminate the bias of choosing specific start and end dates',
              'SEBI mandates only rolling returns to be published',
              'Rolling returns are easier to calculate',
            ],
            correctAnswer: 1,
            explanation:
              'Rolling returns evaluate performance across every possible holding period of a given length, eliminating the bias that comes from selecting specific start and end dates in point-to-point analysis. This provides a comprehensive view of consistency across market cycles.',
          },
        ],

        summaryNotes: [
          'Absolute return = simple percentage gain, used for periods under 1 year; CAGR = annualized compounded return, used for periods over 1 year',
          'XIRR is the only correct method for SIP return measurement — it accounts for different investment dates and amounts of each installment',
          'Rolling returns show performance consistency by calculating returns for every possible n-year period; prefer funds with high average and low standard deviation of rolling returns',
          'SEBI mandates CAGR for periods above 1 year and prohibits annualizing returns for periods below 1 year',
          'Never rely on a single point-to-point return — always cross-check with rolling returns and compare against the benchmark using TRI',
        ],

        relatedTopics: [
          'benchmark-alpha',
          'sebi-return-norms',
          'past-vs-future',
        ],
      },
    },

    // ── Section 2: Benchmark & Alpha ───────────────────────────────────
    {
      id: 'benchmark-alpha',
      title: 'Benchmark & Alpha — Beating the Index',
      slug: 'benchmark-alpha',
      content: {
        definition:
          'A benchmark is a standard reference index against which the performance of a mutual fund is measured. Alpha represents the excess return generated by a fund over and above its benchmark return, adjusted for risk. Positive alpha indicates that the fund manager has added value through security selection or market timing, while negative alpha means the fund has underperformed its benchmark on a risk-adjusted basis. SEBI mandates that every mutual fund scheme must declare a tier-1 benchmark (primary) and a tier-2 benchmark (additional) for performance comparison, and returns must be compared against the Total Return Index (TRI) version of the benchmark, which includes dividends.',

        explanation:
          'A benchmark serves as the reference standard — similar to comparing a student\'s score against the class topper. Every fund is compared to its benchmark to determine whether it is outperforming or underperforming. For example, if a large-cap fund gained 15% in a year but the Nifty 50 TRI gained 18%, that fund has actually underperformed despite showing a seemingly good absolute return, resulting in a negative alpha of -3%. This is the single most important concept for recommending actively managed funds. If a fund consistently fails to beat its benchmark, the investor is better off in a low-cost index fund. Alpha generation has become harder as Indian markets mature — the average large-cap fund alpha has been declining, and passive fund AUM has crossed ₹12 lakh crore, making it the fastest-growing segment. SEBI now mandates benchmark comparison in all performance disclosures. Jensen\'s Alpha adjusts for risk — it measures the excess return above what the Capital Asset Pricing Model (CAPM) would predict for a fund with that level of systematic risk (beta). A fund that takes twice the market risk and delivers twice the market return has zero alpha — it has not added any value, just more risk. True alpha comes from superior stock selection or sector allocation that generates returns beyond what the risk level would predict. In 2018, SEBI mandated that all fund performance must be compared against the TRI (Total Return Index) rather than the price return index. The TRI includes dividends reinvested, making it a higher and fairer bar for comparison. Previously, many funds appeared to generate alpha when in fact the benchmark was understated because it excluded dividends.',

        realLifeExample:
          'Consider the case of two large-cap funds compared over 5 years (2020-2025). Fund A delivered a CAGR of 16.5% while Fund B delivered 14.2%. The Nifty 50 TRI delivered 14.8% over the same period. Fund A has positive alpha of approximately 1.7% (before risk adjustment), meaning the fund manager added value. Fund B has negative alpha of -0.6%, meaning the investor would have been better off in an index fund with a lower expense ratio. An index fund tracking Nifty 50 with a 0.10% expense ratio would have delivered approximately 14.7% (14.8% minus expenses). Fund B at 14.2% with a 1.5% expense ratio has actually destroyed value. This illustrates why SEBI pushed for the TRI comparison — it raises the bar for active managers and supports honest fund recommendations. With Nifty 50 having delivered a long-term CAGR of approximately 12-14% over 20+ years, and the risk-free rate (10-year government bond yield) at approximately 7%, calculating Jensen\'s Alpha becomes instructive. If Fund A has a beta of 1.1: Jensen\'s Alpha = 16.5% - [7% + 1.1 x (14.8% - 7%)] = 16.5% - [7% + 8.58%] = 16.5% - 15.58% = 0.92%. The true risk-adjusted alpha is 0.92%, which is still positive — the fund manager genuinely added value even after accounting for the higher risk taken.',

        keyPoints: [
          'A benchmark is the reference index used to evaluate whether a fund manager has added or destroyed value',
          'Alpha = Fund Return - Benchmark Return (simple alpha); Jensen\'s Alpha adjusts for the risk (beta) taken by the fund',
          'SEBI mandates tier-1 (primary) and tier-2 (additional) benchmarks for every mutual fund scheme',
          'Since 2018, SEBI requires performance comparison against Total Return Index (TRI) which includes dividends reinvested',
          'Positive alpha means the fund manager has outperformed; negative alpha means underperformance relative to benchmark',
          'A fund with high returns but high beta may have zero or negative alpha — returns may just be compensation for higher risk',
          'If an actively managed fund consistently delivers negative alpha, a low-cost index fund is a better choice for the investor',
          'The active vs passive debate hinges on alpha — in efficient markets, generating consistent positive alpha is extremely difficult',
        ],

        formula:
          'Simple Alpha = Fund Return - Benchmark Return\n\nJensen\'s Alpha = Fund Return - [Risk-Free Rate + Beta x (Benchmark Return - Risk-Free Rate)]\n\nThis is derived from the CAPM: Expected Return = Risk-Free Rate + Beta x (Market Return - Risk-Free Rate)\nJensen\'s Alpha measures how much the actual return exceeds the CAPM-predicted return.',

        numericalExample:
          'Given:\nFund Return = 18% per annum\nBenchmark (Nifty 50 TRI) Return = 15% per annum\nRisk-Free Rate (10-year G-Sec yield) = 7%\nFund Beta = 1.15\n\nSimple Alpha = 18% - 15% = +3%\n\nJensen\'s Alpha = 18% - [7% + 1.15 x (15% - 7%)]\n= 18% - [7% + 1.15 x 8%]\n= 18% - [7% + 9.2%]\n= 18% - 16.2%\n= +1.8%\n\nInterpretation: While the simple alpha is 3%, after adjusting for the fund\'s higher risk (beta of 1.15), the true value added by the fund manager is 1.8%. This is still positive, confirming genuine skill — not just higher risk-taking.',

        faq: [
          {
            question: 'What is the difference between a price index and a Total Return Index (TRI)?',
            answer:
              'A price index (like Nifty 50) only tracks the price movement of its constituent stocks. A Total Return Index (TRI) additionally assumes that all dividends paid by constituent stocks are reinvested back into the index. The TRI always shows a higher return than the price index. SEBI mandated TRI comparison from February 2018 because it provides a fairer benchmark — the fund manager has the benefit of dividends, so the benchmark should reflect that too.',
          },
          {
            question: 'Can a fund have high returns but negative alpha?',
            answer:
              'Absolutely. If a fund takes significantly more risk (higher beta) than the benchmark, it may deliver high absolute returns but still have negative Jensen\'s Alpha. For example, a fund with beta of 1.5 is expected to deliver 1.5x the market return. If the market returns 12% and the fund returns 16%, the CAPM expected return would be 7% + 1.5 x (12% - 7%) = 14.5%. The fund returned 16%, so Jensen\'s Alpha is 1.5%. But if the fund only returned 14%, the alpha would be -0.5% despite a seemingly good 14% return.',
          },
          {
            question: 'What are tier-1 and tier-2 benchmarks?',
            answer:
              'Tier-1 benchmark is the primary benchmark most closely aligned with the fund\'s investment universe. For a large-cap fund, it would be Nifty 50 TRI or BSE 100 TRI. Tier-2 benchmark is an additional benchmark for broader comparison, often a wider market index. SEBI requires both to be declared so investors have multiple reference points for evaluating performance.',
          },
          {
            question: 'If most active funds fail to beat the benchmark, why not just use index funds?',
            answer:
              'This is a valid argument and the foundation of the passive investing movement. Data globally and in India shows that over 10-year periods, 60-80% of active large-cap funds fail to beat their benchmark after fees. However, in the mid-cap and small-cap segments in India, active fund managers still have more opportunities to generate alpha due to lower analyst coverage and market inefficiencies. The choice depends on the fund category, time horizon, and the investor\'s belief in active management.',
          },
          {
            question: 'How often should alpha be checked for a fund?',
            answer:
              'Alpha should not be checked on a monthly or quarterly basis — that is too short a period and subject to noise. It is best evaluated on a rolling 3-year and 5-year basis. If a fund has consistently delivered negative rolling 3-year alpha for 8-10 consecutive quarters, it is a strong signal to consider switching. Conversely, a temporary dip in alpha during a sharp market rally (where momentum stocks outperform and quality stocks lag) does not warrant a switch.',
          },
        ],

        mcqs: [
          {
            question:
              'A mutual fund delivered a return of 20% while its benchmark TRI delivered 17%. The fund\'s beta is 1.2 and the risk-free rate is 7%. What is Jensen\'s Alpha?',
            options: ['3.0%', '1.0%', '0.8%', '13.0%'],
            correctAnswer: 1,
            explanation:
              'Jensen\'s Alpha = Fund Return - [Rf + Beta x (Rm - Rf)] = 20% - [7% + 1.2 x (17% - 7%)] = 20% - [7% + 12%] = 20% - 19% = 1.0%. The simple alpha is 3%, but risk-adjusted alpha is only 1.0% because the fund took on more risk (beta 1.2).',
          },
          {
            question:
              'SEBI mandated the use of Total Return Index (TRI) for benchmark comparison from:',
            options: [
              'April 2016',
              'February 2018',
              'October 2019',
              'January 2020',
            ],
            correctAnswer: 1,
            explanation:
              'SEBI mandated that mutual fund performance must be compared against TRI (Total Return Index) benchmarks from February 1, 2018. TRI includes dividend reinvestment, making it a more accurate and fair benchmark for comparison.',
          },
          {
            question:
              'Which of the following statements about alpha is INCORRECT?',
            options: [
              'Positive alpha indicates outperformance relative to benchmark',
              'Jensen\'s Alpha adjusts for the systematic risk taken by the fund',
              'A fund with high returns always has positive alpha',
              'Consistent negative alpha suggests the investor is better off in an index fund',
            ],
            correctAnswer: 2,
            explanation:
              'A fund with high absolute returns can still have negative alpha if the returns are merely compensation for higher risk (higher beta). Alpha must be evaluated on a risk-adjusted basis, not just on absolute return numbers.',
          },
        ],

        summaryNotes: [
          'Benchmark is the reference index for measuring fund performance; alpha measures the excess return generated above the benchmark',
          'Jensen\'s Alpha = Fund Return - [Risk-Free Rate + Beta x (Benchmark Return - Risk-Free Rate)] — it adjusts for risk taken',
          'SEBI mandates TRI (Total Return Index) benchmarks since February 2018, tier-1 and tier-2 benchmarks for every scheme',
          'High absolute return does not guarantee positive alpha — always check risk-adjusted performance before recommending active funds',
          'If a fund consistently shows negative rolling alpha over 3+ years, recommend switching to a low-cost index fund tracking the same benchmark',
        ],

        relatedTopics: [
          'measuring-returns',
          'risk-measures',
          'performance-attribution',
        ],
      },
    },

    // ── Section 3: Risk Measures ───────────────────────────────────────
    {
      id: 'risk-measures',
      title: 'Risk Measures — Standard Deviation, Beta, Sharpe Ratio',
      slug: 'risk-measures',
      content: {
        definition:
          'Risk measures are quantitative metrics used to evaluate the uncertainty and variability of investment returns. Standard Deviation measures the total volatility of a fund\'s returns — higher SD means returns fluctuate more widely around the mean. Beta measures a fund\'s sensitivity to market movements — a beta of 1.2 means the fund tends to move 20% more than the market in either direction. The Sharpe Ratio measures risk-adjusted returns by dividing excess return (over the risk-free rate) by the standard deviation — a higher Sharpe Ratio indicates better return per unit of total risk. Additional measures include the Treynor Ratio (return per unit of systematic risk), Information Ratio (alpha per unit of tracking error), and Sortino Ratio (return per unit of downside risk only).',

        explanation:
          'One of the most common questions in fund analysis is: "How does one compare two funds that have similar returns?" The answer is risk. Returns indicate how much was earned, but risk measures reveal how much uncertainty was endured to earn that return. Consider two funds both delivering 15% CAGR over 5 years. Fund A had a standard deviation of 12% — its returns ranged roughly between 3% and 27% in any given year. Fund B had a standard deviation of 22% — its returns swung between -7% and 37%. Both ended at the same place, but Fund A provided a much smoother ride. For an investor who panics and redeems during a crash, Fund B is dangerous. Beta measures market risk specifically. A fund with beta 0.8 tends to fall less than the market in downturns but also rise less in rallies. A fund with beta 1.3 amplifies market movements in both directions. For conservative investors, low-beta funds are more suitable. For aggressive investors comfortable with volatility, high-beta funds may be appropriate. The Sharpe Ratio, Sortino Ratio, and Information Ratio are all standard metrics used across the industry. The Sharpe Ratio is the single most powerful metric for fund comparison. It answers the question: "For every unit of risk taken, how much extra return is earned above the risk-free rate?" A Sharpe Ratio of 1.0 means 1% excess return for every 1% of volatility. Higher is always better. The Treynor Ratio is similar but uses beta instead of standard deviation — useful when comparing well-diversified portfolios where unsystematic risk is minimal.',

        realLifeExample:
          'Consider three large-cap funds compared over a 5-year period (hypothetical but realistic numbers), using a risk-free rate of 7% (approximate 10-year government bond yield):\n\nFund X: Return 16%, SD 14%, Beta 1.05\nSharpe = (16 - 7) / 14 = 0.64\nTreynor = (16 - 7) / 1.05 = 8.57\n\nFund Y: Return 18%, SD 20%, Beta 1.30\nSharpe = (18 - 7) / 20 = 0.55\nTreynor = (18 - 7) / 1.30 = 8.46\n\nFund Z: Return 14%, SD 10%, Beta 0.85\nSharpe = (14 - 7) / 10 = 0.70\nTreynor = (14 - 7) / 0.85 = 8.24\n\nFund Y has the highest absolute return at 18%, but Fund Z has the best Sharpe Ratio at 0.70 — it delivered the best risk-adjusted return. Fund Z is ideal for a conservative investor. Fund X offers a good balance. Fund Y, despite the highest return, is the least efficient in terms of risk-adjusted performance. This type of analysis is essential for making sound, evidence-based fund recommendations.',

        keyPoints: [
          'Standard Deviation measures total volatility — higher SD means wider fluctuation of returns around the average; useful for comparing funds in the same category',
          'Beta measures sensitivity to market (benchmark) movements — beta > 1 amplifies market moves, beta < 1 dampens them, beta = 1 moves exactly with market',
          'Sharpe Ratio = (Fund Return - Risk-Free Rate) / Standard Deviation — measures return earned per unit of total risk; higher is better',
          'Treynor Ratio = (Fund Return - Risk-Free Rate) / Beta — measures return earned per unit of systematic (market) risk; useful for diversified portfolios',
          'Information Ratio = Alpha / Tracking Error — measures the consistency of a fund manager\'s outperformance relative to the benchmark',
          'Sortino Ratio uses only downside deviation instead of total SD — it penalizes only harmful volatility (negative returns), not upside volatility',
          'Always compare risk metrics of funds within the same category — comparing the SD of a liquid fund with an equity fund is meaningless',
          'A fund with a high return but poor Sharpe Ratio may not be suitable for risk-averse investors — risk-adjusted metrics prevent misleading comparisons',
        ],

        formula:
          'Standard Deviation (SD) = sqrt( (1/(n-1)) x Sum of (Ri - R_mean)^2 )\nwhere Ri = return in period i, R_mean = average return, n = number of periods\n\nBeta = Covariance(Fund Return, Benchmark Return) / Variance(Benchmark Return)\n\nSharpe Ratio = (Rp - Rf) / SD_p\nwhere Rp = portfolio return, Rf = risk-free rate, SD_p = standard deviation of portfolio\n\nTreynor Ratio = (Rp - Rf) / Beta_p\n\nInformation Ratio = (Rp - Rb) / Tracking Error\nwhere Rb = benchmark return, Tracking Error = SD of (Rp - Rb)\n\nSortino Ratio = (Rp - Rf) / Downside Deviation\nwhere Downside Deviation = sqrt( (1/n) x Sum of min(Ri - Rf, 0)^2 )',

        numericalExample:
          'Fund Performance Data (monthly returns for simplicity):\nFund Return (Rp) = 15% per annum\nBenchmark Return (Rb) = 12% per annum\nRisk-Free Rate (Rf) = 7% (10-year G-Sec yield)\nStandard Deviation of Fund (SD_p) = 16%\nBeta of Fund = 1.10\nTracking Error = 4%\n\nSharpe Ratio = (15% - 7%) / 16% = 8% / 16% = 0.50\nInterpretation: For every 1% of volatility, the fund earns 0.50% excess return.\n\nTreynor Ratio = (15% - 7%) / 1.10 = 8% / 1.10 = 7.27\nInterpretation: For every unit of systematic risk, the fund earns 7.27% excess return.\n\nInformation Ratio = (15% - 12%) / 4% = 3% / 4% = 0.75\nInterpretation: An IR above 0.5 is considered good; 0.75 indicates consistent outperformance.\n\nNote: Sharpe Ratio above 1.0 is excellent, 0.5-1.0 is good, below 0.5 is average.',

        faq: [
          {
            question:
              'What is a good Sharpe Ratio for a mutual fund?',
            answer:
              'Generally, a Sharpe Ratio above 1.0 is considered excellent, between 0.5 and 1.0 is good, and below 0.5 is average. However, Sharpe Ratios vary significantly by fund category and market conditions. In a bull market, most equity funds will show high Sharpe Ratios. The key is to compare Sharpe Ratios of funds within the same category and over the same time period — typically 3 or 5 years.',
          },
          {
            question: 'What does a beta of less than 1 mean for an investment?',
            answer:
              'A beta less than 1 means the fund is less volatile than the benchmark. If a fund has a beta of 0.75, it tends to move only 75% as much as the market — when the Nifty falls 10%, the fund is expected to fall about 7.5%, and when the Nifty rises 10%, the fund is expected to rise about 7.5%. Low-beta funds are suitable for conservative investors who prioritize capital protection over aggressive growth.',
          },
          {
            question: 'Why is Sortino Ratio considered better than Sharpe Ratio by some analysts?',
            answer:
              'The Sharpe Ratio penalizes both upside and downside volatility equally. But investors do not mind upside volatility — no one complains when returns exceed expectations. The Sortino Ratio only considers downside deviation (returns below the risk-free rate), making it a more relevant measure of harmful risk. A fund with occasional large positive returns and few negative returns will have a better Sortino Ratio than Sharpe Ratio, correctly reflecting that it is not very risky despite high total volatility.',
          },
          {
            question: 'How is tracking error different from standard deviation?',
            answer:
              'Standard deviation measures the total variability of a fund\'s returns. Tracking error measures the variability of the difference between the fund\'s returns and the benchmark\'s returns. A low tracking error means the fund closely follows its benchmark (typical of index funds, tracking error of 0.1-0.5%). A high tracking error means the fund deviates significantly from the benchmark (typical of active funds). For index funds, lower tracking error is better. For active funds, some tracking error is expected and even desired.',
          },
          {
            question: 'Can these risk measures be used for debt funds as well?',
            answer:
              'Yes, but with different benchmarks and context. For debt funds, modified duration and credit quality serve as additional risk measures. Beta and standard deviation are still relevant but the benchmarks would be bond indices like CRISIL Composite Bond Index. The Sharpe Ratio is particularly useful for comparing debt funds since returns tend to be in a narrow range, and the fund with the best risk-adjusted return is the clear winner.',
          },
        ],

        mcqs: [
          {
            question:
              'A fund has an annual return of 14%, a standard deviation of 18%, and the risk-free rate is 7%. What is the Sharpe Ratio?',
            options: ['0.78', '0.44', '0.39', '0.33'],
            correctAnswer: 2,
            explanation:
              'Sharpe Ratio = (Fund Return - Risk-Free Rate) / Standard Deviation = (14% - 7%) / 18% = 7% / 18% = 0.39. This indicates a below-average risk-adjusted performance — for every 1% of volatility, the fund earns only 0.39% excess return above the risk-free rate.',
          },
          {
            question:
              'A mutual fund has a beta of 1.3. If the benchmark index falls by 10%, the fund is expected to:',
            options: [
              'Fall by exactly 10%',
              'Fall by approximately 13%',
              'Fall by approximately 7.7%',
              'Rise by 3%',
            ],
            correctAnswer: 1,
            explanation:
              'Beta measures the sensitivity of a fund to benchmark movements. A beta of 1.3 means the fund amplifies market moves by 30%. If the benchmark falls 10%, the fund is expected to fall approximately 1.3 x 10% = 13%. Similarly, if the market rises 10%, the fund would be expected to rise approximately 13%.',
          },
          {
            question:
              'Which risk metric specifically measures the consistency of a fund manager\'s ability to outperform the benchmark?',
            options: [
              'Sharpe Ratio',
              'Beta',
              'Information Ratio',
              'Standard Deviation',
            ],
            correctAnswer: 2,
            explanation:
              'The Information Ratio = Alpha / Tracking Error. It measures not just whether the fund outperforms (alpha), but how consistently it does so (tracking error is the variability of the alpha). A high Information Ratio indicates consistent outperformance, while a low one suggests erratic performance relative to the benchmark.',
          },
          {
            question:
              'The Sortino Ratio differs from the Sharpe Ratio primarily because it:',
            options: [
              'Uses beta instead of standard deviation',
              'Considers only downside deviation instead of total standard deviation',
              'Uses the benchmark return instead of the risk-free rate',
              'Measures absolute return rather than excess return',
            ],
            correctAnswer: 1,
            explanation:
              'The Sortino Ratio replaces total standard deviation (used in Sharpe) with downside deviation only. This means it only penalizes negative volatility — returns falling below the risk-free rate — rather than penalizing upside volatility too. This makes it a more investor-centric measure of risk-adjusted return.',
          },
        ],

        summaryNotes: [
          'Standard Deviation measures total volatility; Beta measures market sensitivity; both are essential for understanding different dimensions of risk',
          'Sharpe Ratio (return per unit of total risk) is the most widely used risk-adjusted return metric — always compare funds using Sharpe rather than raw returns alone',
          'Treynor Ratio uses beta instead of SD and is better for well-diversified portfolios; Information Ratio measures alpha consistency; Sortino captures only downside risk',
          'Risk metrics must be compared within the same fund category and over the same time period for meaningful analysis',
          'A Sharpe Ratio above 1.0 is excellent, 0.5-1.0 is good, below 0.5 is average — but always check across market cycles, not just bull markets',
        ],

        relatedTopics: [
          'benchmark-alpha',
          'reading-factsheets',
          'performance-attribution',
        ],
      },
    },

    // ── Section 4: Reading Factsheets ──────────────────────────────────
    {
      id: 'reading-factsheets',
      title: 'Understanding Mutual Fund Factsheets',
      slug: 'reading-factsheets',
      content: {
        definition:
          'A mutual fund factsheet is a monthly document published by every Asset Management Company (AMC) for each scheme, providing a comprehensive snapshot of the fund\'s portfolio, performance, risk metrics, and key operational details. It typically includes the fund manager\'s commentary, portfolio composition (top holdings and sector allocation), key financial ratios (PE, PB for equity; average maturity, modified duration for debt), risk-o-meter classification, AUM (Assets Under Management), NAV history, benchmark comparison, and SIP return tables. SEBI mandates that factsheets be updated and published monthly, and they serve as the primary document for fund analysis and comparison.',

        explanation:
          'If the NAV is the heartbeat of a mutual fund, the factsheet is the full medical report. Every month, the AMC publishes this document, and reading it effectively — like a doctor reads an X-ray — is essential for sound fund analysis. SEBI requires factsheets to include NAV, AUM, expense ratio, portfolio holdings, and benchmark comparison as standard disclosures. Under the new SEBI (Mutual Funds) Regulations 2026, monthly disclosure of portfolio overlap is now mandatory, adding another layer of transparency. Here is what to focus on. First, the fund manager commentary — this is where the fund manager explains the market view and portfolio strategy. Reading between the lines is important: if the fund manager says "we have increased our cash allocation", it likely means they are cautious about valuations. If they say "we have rotated from IT to banking", they see value opportunities in financials. Second, the top 10 holdings and their percentage of the portfolio. If the top stock is 8-10% of AUM, the fund is concentrated — higher risk, higher potential. If the top 10 together are only 30%, the fund is well-diversified. Third, sector allocation should be checked for diversification or concentration. Fourth, risk ratios — SD, Sharpe, Beta — should be studied and compared with category averages. Fifth, for equity funds, the portfolio PE and PB ratios are important. A fund with a PE of 35 in a market where the Nifty PE is around 22-24 is overweight on growth/expensive stocks. Sixth, the risk-o-meter shows SEBI\'s official risk classification from "Low" to "Very High" — this must match the investor\'s risk profile.',

        realLifeExample:
          'Consider the January 2026 factsheet of a popular flexi-cap fund. The fund manager commentary notes a reduction in IT exposure by 3% and increased allocation to auto and banking sectors due to "reasonable valuations and improving earnings outlook." Top 10 holdings make up 42% of AUM — moderately concentrated. The largest holding is Reliance Industries at 7.8%. Sector-wise, Financials are 32%, IT is 14%, Auto is 11%. Risk metrics show: SD of 14.2% (category average 15.1% — lower, good), Sharpe of 0.82 (category average 0.65 — higher, very good), Beta of 0.95 (slightly defensive). Portfolio PE is 24.5 against Nifty PE of around 22-24 — slightly premium but not excessive. AUM is ₹45,000 crores — large but manageable for a flexi-cap. SEBI norms require the factsheet to show returns for 1-year, 3-year, 5-year, and since inception periods, all compared against the benchmark. The SIP returns table shows: 1-year SIP XIRR of 22%, 3-year of 18%, 5-year of 16.5%. Risk-o-meter shows "Very High" — appropriate for a flexi-cap equity fund. This factsheet indicates the fund is well-managed, defensively positioned, and consistently outperforming on a risk-adjusted basis — suitable for an investor with a 5+ year horizon and high risk tolerance.',

        keyPoints: [
          'Factsheets are published monthly by every AMC for every scheme — they are the most important document for ongoing fund analysis',
          'Fund manager commentary reveals the investment thesis, market outlook, and portfolio strategy changes — read it carefully for forward-looking signals',
          'Top 10 holdings show concentration risk — if they exceed 50% of AUM, the fund is highly concentrated; below 35% indicates good diversification',
          'Sector allocation reveals thematic bets — compare against the benchmark sector weights to see active overweight and underweight calls',
          'Key ratios for equity: PE, PB, Sharpe, SD, Beta; for debt: average maturity, modified duration, YTM (Yield to Maturity), credit quality',
          'Risk-o-meter has 6 levels: Low, Low to Moderate, Moderate, Moderately High, High, Very High — must match the investor\'s risk profile',
          'AUM indicates fund size — very large AUM in mid/small-cap can reduce fund manager flexibility; very small AUM increases expense ratio burden',
          'SIP returns table shows XIRR for standard SIP investments over 1, 3, 5, 7, and 10-year periods — use these to set client expectations',
        ],

        faq: [
          {
            question: 'How often should mutual fund factsheets be reviewed?',
            answer:
              'Distributors should review factsheets monthly for their top recommended funds and quarterly for the rest of their coverage universe. Monthly reviews help track portfolio changes, sector rotation, and risk metric trends. However, investment decisions should not be based on a single month\'s factsheet — trends over 3-6 months provide a more reliable picture.',
          },
          {
            question: 'What does the PE ratio of a fund\'s portfolio indicate?',
            answer:
              'The portfolio PE (Price-to-Earnings) ratio is the weighted average PE of all stocks in the fund. A higher PE means the fund holds more expensive or growth-oriented stocks. Compare it with the benchmark PE — if the fund PE is significantly higher, the fund manager is betting on growth stocks. If lower, the manager is value-oriented. Neither is inherently better, but it should align with the fund\'s stated investment style.',
          },
          {
            question: 'What is modified duration in a debt fund factsheet?',
            answer:
              'Modified duration measures the sensitivity of a debt fund\'s NAV to changes in interest rates. A modified duration of 5 years means that for every 1% increase in interest rates, the fund\'s NAV is expected to fall approximately 5%, and vice versa. Higher modified duration means more interest rate risk. In a rising rate environment, prefer funds with lower modified duration.',
          },
          {
            question: 'Is very large AUM a cause for concern?',
            answer:
              'For large-cap and flexi-cap funds, large AUM (even ₹50,000+ crores) is generally not a concern because these funds invest in highly liquid large-cap stocks. However, for mid-cap and small-cap funds, AUM above ₹15,000-20,000 crores can be problematic — the fund manager may struggle to buy meaningful quantities of smaller stocks without moving the price, forcing them to buy more large-caps and diluting the fund\'s character.',
          },
          {
            question: 'What is the risk-o-meter and is it reliable?',
            answer:
              'The risk-o-meter is a SEBI-mandated visual risk indicator with 6 levels from Low to Very High. AMCs must display it on all scheme documents and update it monthly. While it provides a useful at-a-glance risk classification, it has limitations — it is based on the current portfolio and can change. A fund rated "High" today could become "Very High" next month if the portfolio shifts. Always cross-check with actual risk metrics like SD and beta rather than relying solely on the risk-o-meter.',
          },
        ],

        mcqs: [
          {
            question:
              'In a mutual fund factsheet, which of the following metrics is most relevant for assessing interest rate risk of a debt fund?',
            options: [
              'Price-to-Earnings (PE) ratio',
              'Beta',
              'Modified Duration',
              'Sharpe Ratio',
            ],
            correctAnswer: 2,
            explanation:
              'Modified duration measures the sensitivity of a debt fund\'s NAV to interest rate changes. A higher modified duration means greater price sensitivity to rate changes. PE ratio is for equity, beta measures market sensitivity, and Sharpe measures risk-adjusted returns — none are specific to interest rate risk.',
          },
          {
            question:
              'SEBI\'s risk-o-meter classifies mutual fund risk into how many levels?',
            options: ['3', '4', '5', '6'],
            correctAnswer: 3,
            explanation:
              'SEBI\'s risk-o-meter classifies mutual fund schemes into 6 risk levels: Low, Low to Moderate, Moderate, Moderately High, High, and Very High. This classification must be displayed on all scheme-related documents and is updated monthly based on portfolio composition.',
          },
          {
            question:
              'A flexi-cap fund\'s factsheet shows that its top 10 holdings constitute 65% of AUM. This indicates:',
            options: [
              'Excellent diversification',
              'Average diversification',
              'High portfolio concentration',
              'The fund is an index fund',
            ],
            correctAnswer: 2,
            explanation:
              'When top 10 holdings constitute 65% of AUM, the portfolio is highly concentrated — a significant portion of the fund\'s performance depends on a few stocks. While concentration can lead to higher returns if picks work well, it also increases risk. A well-diversified flexi-cap would typically have top 10 holdings at 30-45% of AUM.',
          },
        ],

        summaryNotes: [
          'Mutual fund factsheets are published monthly and are the most comprehensive source for fund analysis — reviewing top fund factsheets monthly is essential practice',
          'Key equity fund factsheet elements: fund manager commentary, top 10 holdings, sector allocation, PE/PB, risk metrics (SD, Sharpe, Beta), risk-o-meter, AUM, and SIP returns',
          'For debt funds, focus on average maturity, modified duration (interest rate sensitivity), YTM, and credit quality distribution',
          'Risk-o-meter has 6 levels (Low to Very High) — mandated by SEBI on all scheme documents; cross-check with actual risk metrics for a complete picture',
          'Watch for concentration risk in top holdings, unusual sector bets vs benchmark, and AUM size implications especially in mid/small-cap funds',
        ],

        relatedTopics: [
          'risk-measures',
          'portfolio-analysis',
          'sebi-return-norms',
        ],
      },
    },

    // ── Section 5: Performance Attribution ─────────────────────────────
    {
      id: 'performance-attribution',
      title: 'Performance Attribution — What Drives Returns?',
      slug: 'performance-attribution',
      content: {
        definition:
          'Performance attribution is an analytical technique that decomposes a mutual fund\'s total return into the specific sources that generated it. The three primary components are: Asset Allocation Effect — the impact of the fund manager\'s decision to overweight or underweight certain asset classes or sectors relative to the benchmark; Security Selection Effect — the impact of choosing specific stocks or bonds within each sector that outperform or underperform their sector peers; and Market Timing Effect — the impact of adjusting portfolio allocation based on short-term market outlook. Style analysis further breaks down performance into growth vs value, large-cap vs mid/small-cap factors. Understanding these sources helps distributors determine whether a fund manager\'s outperformance is due to genuine skill or favourable market conditions.',

        explanation:
          'When an investor asks "why did this fund outperform?", a vague answer is not enough. Performance attribution breaks down the answer scientifically. Suppose a large-cap fund beat the Nifty 50 by 3%. Was it because the fund manager overweighted banking stocks (which rallied 25%) while the benchmark had lower banking allocation? That is the asset allocation effect. Or was it because within the banking sector, the manager picked ICICI Bank (which rose 30%) over SBI (which rose only 15%)? That is the security selection effect. Or did the manager increase equity allocation from 95% to 100% just before a rally, reducing cash at the right time? That is market timing. In reality, most consistent alpha comes from security selection — picking better companies within sectors. Asset allocation decisions are the second biggest contributor. Market timing is the hardest and most unreliable source of alpha — very few fund managers can time the market consistently. This is why the principle "time in the market beats timing the market" remains so important. Style analysis adds another dimension. A fund that outperformed during 2020-2021 might have done so simply because it had a growth/momentum style tilt during a growth-dominated market. When the market rotates to value (as it did in 2022-2023), the same fund may underperform. Understanding style helps set the right expectations and avoid chasing last year\'s winners.',

        realLifeExample:
          'Consider a multi-cap fund that outperformed its benchmark by 4.5% in 2023. Performance attribution reveals:\n\nAsset Allocation Effect: +1.8%\nThe fund had 15% in mid-caps (benchmark had 10%) and mid-caps outperformed large-caps by 12% that year. This overweight contributed 0.6%. The fund also had 5% less in IT (underweight) when IT underperformed, contributing +1.2%.\n\nSecurity Selection Effect: +2.2%\nWithin banking (the largest sector at 30%), the fund held ICICI Bank and Kotak which outperformed SBI and PNB by a wide margin. Within auto, the fund held Tata Motors (which rallied on JLR success) over Maruti.\n\nMarket Timing Effect: +0.5%\nThe fund reduced cash from 5% to 1% in March 2023 during a correction, participating fully in the subsequent rally.\n\nTotal Alpha: 1.8 + 2.2 + 0.5 = 4.5%\n\nThe critical insight here is that the 2.2% from security selection is repeatable — it reflects genuine stock-picking skill. The 0.5% from market timing is likely luck and not repeatable. The 1.8% from asset allocation is partially skill (the deliberate mid-cap overweight) and partially market cycle dependent. A fund where most alpha comes from security selection is more sustainable than one relying on asset allocation or market timing.',

        keyPoints: [
          'Performance attribution decomposes total alpha into three sources: asset allocation effect, security selection effect, and market timing effect',
          'Asset allocation effect comes from overweighting sectors/asset classes that outperform and underweighting those that underperform',
          'Security selection effect comes from picking better individual stocks or bonds within each sector compared to the benchmark constituents',
          'Market timing effect comes from adjusting overall equity/debt/cash allocation based on short-term market views — this is the least reliable source of alpha',
          'Style analysis reveals whether outperformance is driven by growth vs value or large vs small-cap tilts, which may be cyclical rather than skill-based',
          'Consistent alpha from security selection is the strongest signal of fund manager skill and is most likely to persist going forward',
          'Past winners often fail to repeat because their alpha was driven by style or market timing which is cyclical, not by sustainable stock-picking skill',
          'Always check whether outperformance is broad-based across market cycles or concentrated in a specific market phase before concluding on fund manager quality',
        ],

        faq: [
          {
            question: 'Why do past winning funds often underperform in the next cycle?',
            answer:
              'This is called mean reversion and it happens because outperformance is often driven by style factors (growth vs value, large vs small-cap) rather than pure stock-picking skill. A fund that was overweight on growth stocks during a growth rally will naturally outperform, but when the market rotates to value, the same positioning becomes a drag. Additionally, funds that outperform attract large inflows, increasing AUM and potentially reducing the manager\'s ability to generate alpha from smaller stock picks.',
          },
          {
            question: 'How can one tell if alpha is from skill or luck?',
            answer:
              'Three factors help distinguish skill from luck: consistency, source, and market conditions. If a fund consistently outperforms across different market conditions (bull and bear), it is likely skill. If outperformance is concentrated in one year or one market phase, it could be luck or style. Using performance attribution, if most alpha comes from security selection rather than market timing, it is more likely skill. A high Information Ratio (alpha / tracking error > 0.5) also suggests consistent skill rather than random outperformance.',
          },
          {
            question: 'What is style analysis and how does it affect fund selection?',
            answer:
              'Style analysis categorizes fund returns based on their correlation with factors like growth vs value, large-cap vs small-cap, and momentum vs quality. A fund labelled "flexi-cap" might actually have a consistent large-cap growth style tilt, meaning it will perform well when large-cap growth stocks are in favour and underperform when value or mid-caps lead. Understanding style helps investors diversify across styles — not just across fund houses — to build a resilient portfolio.',
          },
          {
            question: 'Is market timing a valid investment strategy for fund managers?',
            answer:
              'Academic research overwhelmingly shows that consistent market timing is extremely difficult and most fund managers who attempt it fail over long periods. The few who appear to time well are often just benefiting from random variation. Even legendary fund managers like Peter Lynch advocated staying fully invested rather than timing. For this reason, performance attribution that shows alpha primarily from market timing should be viewed with scepticism — it is unlikely to persist.',
          },
        ],

        mcqs: [
          {
            question:
              'Performance attribution analysis decomposes a fund\'s alpha into three primary effects. Which of the following is NOT one of them?',
            options: [
              'Asset Allocation Effect',
              'Security Selection Effect',
              'Expense Ratio Effect',
              'Market Timing Effect',
            ],
            correctAnswer: 2,
            explanation:
              'The three primary components of performance attribution are Asset Allocation Effect, Security Selection Effect, and Market Timing Effect. Expense ratio reduces returns but is not a component of performance attribution analysis — it is a separate cost consideration.',
          },
          {
            question:
              'A fund manager overweighted pharmaceutical stocks (25% vs benchmark\'s 15%) during a year when pharma stocks rallied 30% while the broader market returned 15%. The excess return attributable to this decision is primarily:',
            options: [
              'Security selection effect',
              'Asset allocation effect',
              'Market timing effect',
              'Style drift effect',
            ],
            correctAnswer: 1,
            explanation:
              'Overweighting a sector relative to the benchmark is an asset allocation decision. The excess return came from having a higher allocation to pharma (which outperformed), not from selecting specific pharma stocks within the sector. If the manager had picked stocks that beat the pharma sector average, that would be security selection.',
          },
          {
            question:
              'Which source of alpha in performance attribution is considered the most reliable indicator of fund manager skill?',
            options: [
              'Market timing effect',
              'Asset allocation effect',
              'Security selection effect',
              'All three are equally reliable',
            ],
            correctAnswer: 2,
            explanation:
              'Security selection effect — picking better stocks or bonds within each sector — is the most reliable and persistent indicator of genuine fund manager skill. Asset allocation can be partially cyclical (style-driven), and market timing has been consistently shown to be unreliable over long periods. Consistent alpha from stock selection is the gold standard of active management.',
          },
        ],

        summaryNotes: [
          'Performance attribution breaks alpha into asset allocation effect (sector bets), security selection effect (stock picking), and market timing effect (tactical allocation shifts)',
          'Security selection is the most sustainable and skill-driven source of alpha; market timing is the least reliable and often just luck',
          'Past winners may not repeat because outperformance often comes from style tilts (growth/value, large/small) that are cyclical in nature',
          'Style analysis helps identify hidden factor exposures — a "flexi-cap" fund may consistently behave like a large-cap growth fund',
          'A high Information Ratio (above 0.5) combined with alpha primarily from security selection is the best evidence of genuine fund manager skill',
        ],

        relatedTopics: [
          'benchmark-alpha',
          'risk-measures',
          'past-vs-future',
        ],
      },
    },

    // ── Section 6: SEBI Return Norms ───────────────────────────────────
    {
      id: 'sebi-return-norms',
      title: 'SEBI Norms for Representing Returns',
      slug: 'sebi-return-norms',
      content: {
        definition:
          'SEBI (Securities and Exchange Board of India) has established comprehensive guidelines governing how mutual fund returns must be represented in all scheme-related documents, advertisements, and communications. These norms mandate that returns must be shown for standardized periods (1, 3, 5 years, and since inception), must be compared against the TRI (Total Return Index) benchmark, must be in CAGR format for periods exceeding one year, must not be annualized for periods less than one year, and must be accompanied by the risk-o-meter and standard disclaimers including "past performance may or may not be sustained in the future." These regulations exist to prevent misleading representation of fund performance and protect investor interests.',

        explanation:
          'SEBI strictly regulates how mutual fund returns are represented, and both AMCs and distributors must follow these rules. SEBI norms for representing returns mandate disclosure across 1-year, 3-year, 5-year, and since inception periods — all mandatory in factsheets. Cherry-picking only the best period is not allowed. All returns for periods greater than 1 year must be shown as CAGR. Stating "this fund gave 80% in 3 years" is non-compliant — the correct representation is "this fund gave a CAGR of 21.6% over 3 years." Critically, returns for periods less than 1 year must be shown as absolute returns and must NOT be annualized. If a fund gave 8% in 6 months, representing it as "16% annualized" is misleading and violates SEBI norms. All performance comparison must be against the TRI benchmark, not the price return index. SEBI mandates benchmark comparison in all performance disclosures. The risk-o-meter and the disclaimer about past performance must accompany all return data. There are also specific rules for different types of advertisements. The NISM exam frequently tests on these norms, especially the prohibition on annualizing sub-one-year returns and the TRI mandate. One of the most common compliance mistakes among new distributors is showing annualized returns for recent 3-month or 6-month periods to make funds appear more attractive — this is a clear regulatory violation.',

        realLifeExample:
          'For example, consider a compliant client presentation for a large-cap fund:\n\nScheme: ABC Large Cap Fund - Direct Growth\nBenchmark: Nifty 50 TRI\n\n6 months: Fund 9.2% | Benchmark 8.5% (Absolute returns — NOT annualized)\n1 year: Fund 18.5% | Benchmark 16.2% (Point-to-point absolute return)\n3 years: Fund 14.8% CAGR | Benchmark 13.5% CAGR\n5 years: Fund 16.2% CAGR | Benchmark 14.9% CAGR\nSince inception (8 years): Fund 15.1% CAGR | Benchmark 13.8% CAGR\n\nRisk-o-meter: Very High\n\nDisclaimer: "Past performance may or may not be sustained in the future. The returns shown are for the Direct Growth option. Different plans may have different expense ratios and hence different returns."\n\nThe following practices are non-compliant: showing only the 1-year return (which is the highest), annualizing the 6-month return as 18.4%, comparing against the Nifty 50 price return index instead of TRI, or omitting the risk-o-meter. Violating any of these norms can result in SEBI action against both the AMC and the distributor.',

        keyPoints: [
          'Returns must be shown for standardized periods: 1 year, 3 years, 5 years, and since inception — cherry-picking specific periods is not allowed',
          'Returns for periods exceeding 1 year must be represented as CAGR (Compounded Annualized Growth Rate)',
          'Returns for periods less than 1 year must be shown as absolute (point-to-point) returns and must NOT be annualized under any circumstance',
          'All fund returns must be compared against the benchmark\'s Total Return Index (TRI), which includes dividends reinvested',
          'The risk-o-meter must be displayed alongside returns in all scheme-related documents and advertisements',
          'The standard disclaimer "past performance may or may not be sustained in future" is mandatory in all communications showing fund performance',
          'Advertisements must comply with SEBI\'s advertisement code — making tall claims, showing selective periods, or guaranteeing returns is prohibited',
          'Both AMCs and distributors can face regulatory action for non-compliant representation of returns',
        ],

        faq: [
          {
            question: 'Why does SEBI prohibit annualizing returns for periods less than 1 year?',
            answer:
              'Annualizing short-period returns can create a highly misleading picture. If a fund earned 5% in 2 months, annualizing it would show 30% — suggesting spectacular performance that may not sustain. Short-period returns are heavily influenced by market conditions and do not reflect the fund\'s long-term capability. SEBI\'s rule protects investors from being lured by inflated annualized short-term numbers.',
          },
          {
            question: 'Can returns be shown for a custom period like 2 years or 7 years?',
            answer:
              'Yes, returns can be shown for additional custom periods beyond the mandatory 1, 3, 5-year and since inception periods. However, the mandatory periods must always be included first. Any custom period exceeding 1 year must also be shown as CAGR. Showing only a custom period that happens to look good (like "2 years" when 1-year and 3-year look bad) without the mandatory periods would be a violation.',
          },
          {
            question: 'What is the difference between Direct and Regular plan returns in disclosures?',
            answer:
              'Both Direct and Regular plan returns must be disclosed where applicable. The Direct plan will always show higher returns because it has no distributor commission embedded in the expense ratio. SEBI requires that when showing returns, the plan type must be clearly mentioned. A distributor should show Regular plan returns (which reflect what the client actually earns through the distributor channel) while being transparent about the Direct plan option.',
          },
          {
            question: 'Are there penalties for non-compliant return representation?',
            answer:
              'Yes, SEBI can take action against both AMCs and distributors for non-compliant return representation. Penalties can include warnings, monetary fines, suspension of registration, or cancellation of ARN (AMFI Registration Number) for distributors. AMFI also has its own code of conduct that distributors must follow. The most common violations are annualizing sub-1-year returns, cherry-picking periods, and not using TRI benchmarks.',
          },
          {
            question: 'Do these norms apply to social media posts and WhatsApp forwards by distributors?',
            answer:
              'Yes, absolutely. SEBI\'s advertisement code applies to all forms of communication — print, digital, social media, messaging apps, emails, and verbal communication. If a distributor shares fund performance data on WhatsApp or Instagram, it must comply with all the same norms: mandatory periods, CAGR for above 1 year, no annualization for below 1 year, TRI benchmark comparison, risk-o-meter, and disclaimer. Many distributors have received SEBI show-cause notices for non-compliant social media posts.',
          },
        ],

        mcqs: [
          {
            question:
              'A mutual fund earned 6% in the last 4 months. As per SEBI norms, how should this return be represented?',
            options: [
              '18% annualized return',
              '6% absolute return for 4 months',
              '6% CAGR',
              'Either annualized or absolute, at the distributor\'s discretion',
            ],
            correctAnswer: 1,
            explanation:
              'As per SEBI norms, returns for periods less than 1 year must be shown as absolute (point-to-point) returns and must NOT be annualized. Showing "18% annualized" for a 4-month return is misleading and a clear regulatory violation. The correct representation is "6% absolute return for 4 months."',
          },
          {
            question:
              'Which of the following is mandatory when presenting mutual fund performance as per SEBI guidelines?',
            options: [
              'Comparison with the top-performing fund in the category',
              'Comparison with the scheme\'s benchmark using Total Return Index (TRI)',
              'Comparison with bank fixed deposit rates',
              'Comparison with the inflation rate',
            ],
            correctAnswer: 1,
            explanation:
              'SEBI mandates that mutual fund performance must be compared against the scheme\'s declared benchmark using the Total Return Index (TRI), which includes dividends reinvested. Comparison with other funds, FD rates, or inflation is optional and supplementary — only the TRI benchmark comparison is mandatory.',
          },
          {
            question:
              'As per SEBI norms, the minimum standardized periods for which mutual fund returns must be disclosed are:',
            options: [
              '1 year and 3 years only',
              '1 year, 3 years, and 5 years',
              '1 year, 3 years, 5 years, and since inception',
              '3 years, 5 years, 10 years, and since inception',
            ],
            correctAnswer: 2,
            explanation:
              'SEBI requires that mutual fund returns be disclosed for 1 year, 3 years, 5 years, and since inception as minimum mandatory periods. If the fund has not completed 5 years, since inception returns suffice. This prevents cherry-picking of favourable time periods.',
          },
          {
            question:
              'The standard risk disclaimer that must accompany mutual fund performance data states:',
            options: [
              '"Investments in mutual funds are subject to market risks"',
              '"Past performance may or may not be sustained in the future"',
              '"Mutual funds are guaranteed to give positive returns over 5 years"',
              '"Returns are guaranteed by SEBI"',
            ],
            correctAnswer: 1,
            explanation:
              'The mandatory disclaimer is "past performance may or may not be sustained in the future." While "investments are subject to market risks" is also a common disclaimer, the specific disclaimer about past performance is mandated alongside return data presentation. Returns are never guaranteed by any regulator.',
          },
        ],

        summaryNotes: [
          'SEBI mandates returns for 1, 3, 5 years and since inception — no cherry-picking of favourable periods is allowed',
          'Above 1 year: CAGR mandatory; Below 1 year: absolute return only, annualization is strictly prohibited',
          'All performance must be benchmarked against TRI (Total Return Index) — not the price return index — since February 2018',
          'Risk-o-meter and "past performance may or may not be sustained" disclaimer are mandatory alongside all return disclosures',
          'These norms apply to ALL communication channels including social media, WhatsApp, and verbal presentations — non-compliance can result in SEBI action and ARN cancellation',
        ],

        relatedTopics: [
          'measuring-returns',
          'benchmark-alpha',
          'reading-factsheets',
        ],
      },
    },

    // ── Section 7: Past vs Future Performance ──────────────────────────
    {
      id: 'past-vs-future',
      title: 'Reading Fund Performance — Past Performance vs Future',
      slug: 'past-vs-future',
      content: {
        definition:
          'The relationship between past performance and future performance of mutual funds is one of the most studied topics in finance. While past performance data is the primary tool available for evaluating funds, extensive research consistently shows that past returns do not reliably predict future returns. Consistency of performance — measured through rolling returns, performance across market cycles, and capture ratios — is a more meaningful indicator than absolute past returns. Capture ratios measure what percentage of the benchmark\'s upside a fund captures during rallies (upside capture) and what percentage of the downside it suffers during falls (downside capture). An ideal fund captures more upside and less downside than the benchmark.',

        explanation:
          'This is one of the most critical lessons in fund evaluation. Investors frequently seek the "best performing fund" by looking at Value Research or Morningstar ratings, pointing to the highest return over 1 or 3 years. However, research consistently shows that top-performing funds in one period are no more likely to be top performers in the next period than a coin flip. The reasons are clear — outperformance is often driven by market cycles, style factors, or one-time events rather than repeatable skill. With the Sensex having crossed 85,000+ levels and Nifty 50 crossing 26,000+, many funds show impressive recent returns, but the focus should be on consistency, not peak returns. A fund that ranks in the top 25% across multiple rolling 3-year periods is far more reliable than one that was number 1 in one period but number 50 in the next. Rolling return analysis remains the most reliable way to evaluate fund performance. Checking how a fund performed not just in bull markets but also in bear markets is essential. A fund that falls less than its benchmark during crashes (low downside capture ratio) and participates well in rallies (high upside capture ratio) represents an ideal investment. Capture ratios below 100% on the downside and above 100% on the upside indicate genuine fund manager skill in managing risk and capturing opportunity. Importantly, fund switches should not be based on 6 months of underperformance — that is noise. But if a fund consistently underperforms its benchmark over 6-8 rolling quarters (18-24 months), has had a change in fund manager, or has experienced significant style drift, those are legitimate reasons to evaluate alternatives.',

        realLifeExample:
          'In 2017, small-cap funds were the top performers with many delivering 40-60% returns. Investors and distributors piled in. By 2018-2019, the same small-cap funds fell 30-50%, wiping out years of gains for those who invested at the peak based on past returns. Meanwhile, a balanced advantage fund that delivered a "boring" 12% in 2017 fell only 5% in 2018 and recovered quickly — the consistent performer protected wealth better.\n\nLet us look at capture ratios for a specific fund. Suppose a large-cap fund has an upside capture ratio of 95% and a downside capture ratio of 75% measured over 5 years. This means: when the Nifty 50 rallied 10%, this fund typically gained 9.5%. But when the Nifty fell 10%, this fund only fell 7.5%. Over multiple cycles, this asymmetry compounds powerfully. If the Nifty went up 20% then down 15%, a ₹1,00,000 investment in the Nifty would become ₹1,02,000. The same amount in this fund would become ₹1,04,975 (up 19%, then down only 11.25%). That 3% difference in one cycle compounds massively over 10-20 years.\n\nThe following are legitimate triggers for considering a fund change: (1) Negative rolling 3-year alpha for 6+ consecutive quarters, (2) Fund manager change — especially if the new manager has a different style, (3) AUM bloat in a mid/small-cap fund making it difficult to maintain its investment approach, (4) Consistent style drift from the fund\'s mandate, (5) Regulatory issues with the AMC.',

        keyPoints: [
          'Past performance does not predict future returns — this is backed by decades of global and Indian market research',
          'Consistency of performance across market cycles is far more important than peak absolute returns in any single period',
          'Rolling return analysis is the best tool for assessing consistency — check 3-year and 5-year rolling returns across different market phases',
          'Upside capture ratio above 100% means the fund gains more than the benchmark in rallies; downside capture below 100% means it falls less in corrections',
          'The ideal fund has high upside capture and low downside capture — this asymmetry compounds powerfully over long periods',
          'Do not switch funds based on short-term underperformance (less than 12-18 months) — that is often just market noise or style rotation',
          'Legitimate reasons to change a fund: persistent negative alpha over 6+ quarters, fund manager change, significant AUM bloat, style drift, or regulatory concerns',
          'Star ratings and short-term rankings can be misleading — a 5-star fund today can become 3-star within a year as the market cycle turns',
        ],

        faq: [
          {
            question: 'If past performance does not predict future returns, how should funds be selected?',
            answer:
              'Focus on process rather than outcomes. Look for consistency of rolling returns (not just point-to-point returns), favourable capture ratios, experienced fund managers with a clear investment philosophy, reasonable AUM for the fund category, and low tracking error for the stated strategy. A fund that consistently ranks in the top 30% across different periods is a better bet than one that was number 1 in one period but number 50 in another. Also consider the expense ratio — lower costs provide a structural advantage.',
          },
          {
            question: 'What are capture ratios and how are they interpreted?',
            answer:
              'Upside capture ratio measures what percentage of the benchmark\'s positive returns the fund captures during up-markets. Downside capture ratio measures what percentage of the benchmark\'s negative returns the fund suffers during down-markets. Ideal: upside capture > 100% (fund gains more than benchmark in rallies) and downside capture < 100% (fund falls less than benchmark in corrections). For example, upside capture of 110% and downside capture of 80% means the fund amplifies gains but cushions losses — excellent risk management.',
          },
          {
            question: 'How long should one wait before deciding a fund is underperforming?',
            answer:
              'For equity funds, at least 3 years of data is needed to draw meaningful conclusions, and even that should ideally cover at least one full market cycle. Short-term underperformance of 6-12 months is often just noise or style rotation. However, if a fund has underperformed its benchmark on a rolling 3-year basis for 6 consecutive quarters (18 months), that is a strong signal worth investigating further. Quantitative analysis should be combined with qualitative factors like fund manager stability and investment process consistency.',
          },
          {
            question: 'Should star ratings from Morningstar or Value Research be relied upon for fund selection?',
            answer:
              'Star ratings are a useful starting point for shortlisting, but they should never be the sole selection criterion. Ratings are backward-looking — they measure past risk-adjusted performance, not future potential. A 5-star fund has performed well in the recent past, but this rating can change significantly within a year. Use ratings to create a shortlist, then do deeper analysis on rolling returns, capture ratios, fund manager track record, and portfolio characteristics before making a recommendation.',
          },
          {
            question: 'What is "style drift" and why is it a concern?',
            answer:
              'Style drift occurs when a fund gradually changes its investment style or portfolio composition away from its stated mandate. For example, a large-cap fund that starts holding 25% in mid-caps, or a value fund that buys growth stocks. This is a concern because the investor invested based on a specific risk-return expectation. Style drift can expose the investor to unintended risks and disrupt their overall portfolio asset allocation. SEBI now monitors style drift more closely and has set category-specific rules.',
          },
        ],

        mcqs: [
          {
            question:
              'A fund has an upside capture ratio of 110% and a downside capture ratio of 85%. This means:',
            options: [
              'The fund is more volatile than the benchmark in all market conditions',
              'The fund gains more than the benchmark in up-markets and loses less in down-markets',
              'The fund always outperforms the benchmark',
              'The fund has a beta greater than 1',
            ],
            correctAnswer: 1,
            explanation:
              'An upside capture ratio of 110% means the fund captures 110% of the benchmark\'s gains during up-markets (gains more). A downside capture of 85% means the fund suffers only 85% of the benchmark\'s losses during down-markets (falls less). This asymmetry — gaining more and losing less — is the hallmark of skilled fund management and compounds powerfully over time.',
          },
          {
            question:
              'Which of the following is the most reliable method to assess a mutual fund\'s consistency of performance?',
            options: [
              'Looking at the fund\'s 1-year return',
              'Checking the fund\'s star rating on a rating website',
              'Analyzing rolling 3-year and 5-year returns across different market phases',
              'Comparing the fund\'s NAV growth chart',
            ],
            correctAnswer: 2,
            explanation:
              'Rolling return analysis across different market phases (bull, bear, sideways) is the most reliable method for assessing consistency. It shows how the fund performed not just at one point in time but across every possible holding period. Single-period returns, star ratings, and NAV charts can all be misleading as they are heavily influenced by start and end dates.',
          },
          {
            question:
              'Which of the following is a legitimate reason to recommend switching a mutual fund?',
            options: [
              'The fund underperformed the benchmark by 2% in the last 3 months',
              'A colleague recommended a different fund with higher recent returns',
              'The fund has shown persistent negative rolling 3-year alpha for 6+ consecutive quarters',
              'The stock market is expected to fall next quarter',
            ],
            correctAnswer: 2,
            explanation:
              'Persistent negative rolling 3-year alpha for 6+ consecutive quarters (approximately 18 months) is a strong quantitative signal of sustained underperformance and a legitimate reason to evaluate alternatives. Short-term underperformance (3 months), peer recommendations based on recent returns, and market timing predictions are not valid reasons for switching.',
          },
        ],

        summaryNotes: [
          'Past performance does not guarantee future results — top funds in one period often fail to repeat in the next; consistency matters more than peak returns',
          'Use rolling returns (3-year and 5-year) across market cycles as the primary tool for evaluating fund consistency, not point-to-point returns',
          'Capture ratios reveal risk management quality: upside capture > 100% and downside capture < 100% indicate the fund gains more and loses less than the benchmark',
          'Do not switch funds based on less than 18 months of underperformance; legitimate switch triggers include persistent negative alpha, fund manager change, AUM bloat, and style drift',
          'Star ratings and rankings are backward-looking and should be a starting point for shortlisting, not the basis for final fund selection',
        ],

        relatedTopics: [
          'measuring-returns',
          'performance-attribution',
          'portfolio-analysis',
        ],
      },
    },

    // ── Section 8: Portfolio Analysis ──────────────────────────────────
    {
      id: 'portfolio-analysis',
      title: 'Portfolio Analysis — Top Holdings, Sector Allocation, AUM',
      slug: 'portfolio-analysis',
      content: {
        definition:
          'Portfolio analysis is the examination of a mutual fund\'s underlying holdings, sector allocation, asset mix, and structural characteristics to assess its risk profile, diversification quality, and investment style. Key elements include: top holdings analysis (concentration risk from the largest positions), sector allocation (diversification across industries), AUM (Assets Under Management) implications (impact of fund size on flexibility and performance), portfolio turnover (frequency of buying and selling, affecting costs), overlap analysis (checking if multiple funds in a portfolio hold the same underlying stocks), and cash holding levels (indicating the fund manager\'s market view and liquidity management). Under the new SEBI (Mutual Funds) Regulations 2026, monthly disclosure of portfolio overlap is now mandatory, enhancing transparency further. Together, these provide a comprehensive picture of what an investor is actually invested in, beyond just the fund name.',

        explanation:
          'A truth most investors do not realize is that when they own 4 mutual funds, they might think they are diversified, but if all 4 funds hold the same top 10 stocks, they are actually heavily concentrated. This is why portfolio analysis matters — looking under the hood of every fund ensures the overall portfolio is truly diversified. Top holdings analysis: The top 10 stocks and their combined weight reveal concentration risk. In a diversified equity fund, if the top 10 exceed 50%, the fund is concentrated. If the largest single stock is above 8-10%, one stock\'s bad quarter can drag the entire fund. Sector allocation: A fund that has 40% in financials might do well when banks rally but will suffer heavily in a banking crisis. Comparing sector weights against the benchmark helps identify deliberate bets — any overweight of more than 5-7% is a deliberate bet by the fund manager. AUM implications: For large-cap funds, AUM matters less because the stocks are highly liquid. But for a small-cap fund, if AUM crosses ₹15,000-20,000 crores, the fund manager faces a liquidity problem — they cannot buy meaningful quantities of small stocks without moving the price, often forcing them to buy mid-cap or even large-cap stocks, diluting the fund\'s character. Portfolio turnover: Measured as a percentage, it indicates how frequently the fund manager trades. High turnover (above 100%) means the entire portfolio is changed within a year — this increases transaction costs and tax implications (equity STCG at 20%, LTCG at 12.5% with ₹1.25 lakh exemption), eating into returns. Overlap analysis: If an investor holds 3 large-cap funds, chances are all three hold HDFC Bank, Reliance, Infosys, and TCS. The investor has paid three expense ratios for essentially the same exposure. Smart portfolio construction minimizes overlap.',

        realLifeExample:
          'Consider the case of Sunil, who holds three equity funds thinking he is diversified:\n\nFund A (Large Cap): Top holdings — HDFC Bank (9%), Reliance (8%), Infosys (7%), ICICI Bank (6%), TCS (5%). Financials 35%, IT 22%.\nFund B (Flexi Cap): Top holdings — Reliance (7%), HDFC Bank (6%), ICICI Bank (5%), Infosys (5%), Bharti Airtel (4%). Financials 30%, IT 18%.\nFund C (Large & Mid Cap): Top holdings — ICICI Bank (6%), Reliance (6%), HDFC Bank (5%), SBI (4%), Infosys (4%). Financials 33%, IT 16%.\n\nOverlap analysis: HDFC Bank appears in all three funds (combined weight roughly 20% of total portfolio). Reliance appears in all three (21%). Infosys in all three (16%). ICICI Bank in all three (17%). Effective financial sector exposure: 33% across the portfolio. Effective IT exposure: 19%.\n\nSunil thinks he has three different funds, but his actual portfolio is essentially one large-cap fund with heavy financial and IT exposure, and he is paying three expense ratios for it. A better approach: keep Fund A for large-cap exposure, replace Fund B with a mid-cap fund with different top holdings, and replace Fund C with a value-oriented or focused fund. This gives genuine diversification across market caps, styles, and stock names.\n\nCash holdings analysis adds another dimension: Fund A holds 2% cash (fully invested — bullish). Fund B holds 7% cash (cautious — building a war chest for future opportunities). Fund C holds 1% cash (fully deployed). A fund with unusually high cash (above 5-8%) may be signaling that the fund manager considers the market overvalued and is waiting for a correction to deploy capital.',

        keyPoints: [
          'Top 10 holdings exceeding 50% of AUM indicate high concentration risk — one or two stocks can significantly impact fund performance',
          'Sector allocation reveals thematic bets — compare against benchmark weights to identify deliberate overweight and underweight positions',
          'Large AUM in small-cap and mid-cap funds (above ₹15,000-20,000 crores) can constrain the fund manager\'s flexibility and dilute the fund\'s character',
          'Portfolio turnover above 100% indicates the entire portfolio is being replaced within a year — this increases costs and may indicate a short-term trading approach',
          'Overlap analysis is critical for multi-fund portfolios — holding multiple funds with the same top stocks gives false diversification while paying multiple expense ratios',
          'Cash holding levels indicate the fund manager\'s market view — very high cash (above 5-8%) may signal caution about market valuations',
          'Always analyse the total portfolio across all funds, not just individual funds — true diversification is at the portfolio level, not the fund level',
          'Use tools like Value Research or Morningstar portfolio overlap checker to identify duplicate exposures before recommending additional funds',
        ],

        faq: [
          {
            question: 'How can portfolio overlap between two mutual funds be checked?',
            answer:
              'Several free tools are available for overlap analysis. Value Research, Morningstar India, and Kuvera all offer portfolio overlap checkers where two funds can be selected to see what percentage of holdings are common. As a rule of thumb, if two funds have more than 40% overlap in their top 25 holdings, they are not providing meaningful diversification. To reduce overlap, combining funds from different categories (large-cap with mid-cap), different styles (growth with value), or different fund houses with distinct investment approaches is recommended.',
          },
          {
            question: 'What is an ideal portfolio turnover ratio?',
            answer:
              'There is no single ideal number — it depends on the fund\'s strategy. For a buy-and-hold large-cap fund, a turnover of 20-40% is typical and healthy. For an actively managed flexi-cap fund, 50-80% is reasonable. Turnover above 100% suggests frequent trading, which increases transaction costs and short-term capital gains tax (equity STCG is 20%), eating into returns. However, some strategies (like momentum or quant funds) naturally have higher turnover. Compare turnover within the same category for meaningful comparison.',
          },
          {
            question: 'Does large AUM always hurt fund performance?',
            answer:
              'No, it depends on the fund category. For large-cap and index funds, large AUM is generally not a problem because the underlying stocks are highly liquid — even ₹50,000+ crore AUM can be managed efficiently. For mid-cap funds, AUM above ₹20,000 crores starts becoming challenging. For small-cap funds, ₹10,000-15,000 crores can be problematic as the fund manager may struggle to buy meaningful positions in smaller companies without impacting prices. Some successful small-cap funds have closed to new inflows to manage this issue.',
          },
          {
            question: 'What do high cash levels in a fund indicate?',
            answer:
              'Cash levels above 5-8% in an equity fund typically indicate one of three things: (1) The fund manager is cautious about market valuations and is holding cash to deploy during a correction — this is a tactical call. (2) The fund has received large recent inflows and has not yet deployed the money — this is temporary. (3) The fund is a balanced advantage or dynamic asset allocation fund where high cash is by design. For pure equity funds, consistently high cash levels can be a drag on returns during bull markets, so check whether this is a temporary position or a persistent pattern.',
          },
          {
            question: 'How many mutual funds should an investor ideally hold?',
            answer:
              'For most retail investors, 4-6 well-chosen funds across different categories provide adequate diversification without excessive complexity or overlap. A typical structure could be: 1 large-cap or index fund, 1 flexi-cap or mid-cap fund, 1 small-cap fund (if risk appetite permits), 1 hybrid/balanced fund, and 1-2 debt funds. Holding more than 8-10 equity funds almost always leads to significant overlap, making the portfolio behave like an expensive index fund. Quality of selection matters more than quantity.',
          },
        ],

        mcqs: [
          {
            question:
              'An investor holds three large-cap mutual funds. Portfolio overlap analysis shows 55% common holdings across all three funds. This primarily indicates:',
            options: [
              'The investor has excellent diversification',
              'The investor is paying three expense ratios for substantially similar exposure',
              'The funds are outperforming the benchmark',
              'The investor should add more large-cap funds',
            ],
            correctAnswer: 1,
            explanation:
              'A 55% overlap means more than half the portfolio holdings are identical across all three funds. The investor is essentially paying three expense ratios for the same stock exposure, creating false diversification. The solution is to consolidate into one large-cap fund and diversify the remaining allocation into different categories or styles.',
          },
          {
            question:
              'A small-cap mutual fund has grown its AUM from ₹3,000 crores to ₹25,000 crores in two years. This could potentially:',
            options: [
              'Improve the fund\'s performance due to economies of scale',
              'Have no impact on performance',
              'Reduce the fund manager\'s flexibility to invest in small-cap stocks',
              'Automatically make it a mid-cap fund',
            ],
            correctAnswer: 2,
            explanation:
              'Large AUM in a small-cap fund constrains the fund manager\'s flexibility. With ₹25,000 crores, buying meaningful quantities of small-cap stocks (which have low liquidity and market cap) becomes difficult without moving the price. The manager may be forced to buy mid-cap or large-cap stocks, diluting the fund\'s small-cap character and potentially reducing alpha generation.',
          },
          {
            question:
              'A mutual fund with a portfolio turnover ratio of 150% per annum indicates that:',
            options: [
              'The fund manager holds stocks for an average of 8 months',
              'The fund is an index fund',
              'The entire portfolio has been changed 1.5 times during the year',
              'Both (a) and (c)',
            ],
            correctAnswer: 3,
            explanation:
              'A turnover of 150% means the value of stocks bought or sold equals 1.5 times the average AUM during the year — the entire portfolio has been turned over 1.5 times. This also implies an average holding period of approximately 8 months (12/1.5). Both statements (a) and (c) are correct. High turnover increases transaction costs and may trigger short-term capital gains tax.',
          },
          {
            question:
              'A fund holding 8% of its equity AUM in cash while markets are at all-time highs most likely indicates:',
            options: [
              'The fund has poor liquidity management',
              'The fund manager is cautious about valuations and preserving dry powder for future opportunities',
              'The fund is underperforming due to low equity exposure',
              'SEBI has mandated minimum cash holdings',
            ],
            correctAnswer: 1,
            explanation:
              'When markets are at all-time highs, a fund manager holding above-normal cash levels (8% vs typical 2-3%) is often signaling caution about stretched valuations. They are preserving "dry powder" — capital ready to deploy when markets correct and attractive buying opportunities emerge. While this may cause slight underperformance during continued rallies, it provides a cushion and buying opportunity during corrections. SEBI does not mandate minimum cash holdings for equity funds.',
          },
        ],

        summaryNotes: [
          'Portfolio analysis goes beyond fund names — check top holdings, sector allocation, AUM, turnover, overlap, and cash levels to understand true exposure',
          'Overlap analysis is critical: if multiple funds hold the same top stocks, the client has false diversification while paying multiple expense ratios — keep overlap below 40%',
          'AUM matters most for small-cap and mid-cap funds — very large AUM constrains flexibility; for large-cap and index funds, AUM impact is minimal',
          'High portfolio turnover (above 100%) increases costs and tax drag; low turnover with consistent alpha suggests a patient, conviction-based investment approach',
          'Ideal retail portfolio: 4-6 funds across different categories and styles, minimizing overlap while ensuring genuine diversification at the total portfolio level',
        ],

        relatedTopics: [
          'reading-factsheets',
          'risk-measures',
          'past-vs-future',
        ],
      },
    },
  ],
};
